openapi: 3.0.0
info:
  title: URL Shortener
  description: This is a set of apis to manage URL shortener functionalities
  license:
    name: URL Shortener
  version: 1.0.0
servers:
- url: http://localhost:8000
  description: Localhost Url
tags:
- name: Public
  description: APIs for Management of the matrix Bot.
paths:
  /urls:
    get:
      tags:
      - Public
      summary: Fetch all the shortened urls. If any specific shortened url is given, then only the corresponding result is given. Else all the  shortened_url and their corresponding original url is returned.
      description: |
        Fetch all the shortened urls.
      operationId: fetchAllUrls
      parameters:
      - name: shortened_url
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully returned all available shortened urls.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                x-content-type: application/json
              examples:
                Return all the active rooms on the matrix server:
                  value:
                    - "shortened_url": "https://short-url.ly/0000000"
                      "original_url": "https://wikipedia0.com"
        "401":
          description: Unauthorized user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
        "404":
          description: Incorrect endpoint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
        "500":
          description: Error in db connection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
      x-swagger-router-controller: Public
    post:
      tags:
      - Public
      summary: Create shortened url.
      description: |
        Fetch all the shortened urls.
      operationId: shortenUrl
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/urls_body'
      responses:
        "200":
          description: Successfully created the shortened url.
          content:
            application/json:
              schema:
                type: object
                items:
                  type: object
                x-content-type: application/json
              examples:
                Successfully created short url:
                  value:
                    message: Successfully created the short url
                    original_url: https://wikipedia.com
                    shortened_url: https://shortened_url.ly/0000000
                    timestamp: "2022-03-12T15:12:34.123"
        "401":
          description: Unauthorized user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
        "404":
          description: Incorrect endpoint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
        "500":
          description: Error in db connection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
      x-swagger-router-controller: Public
components:
  schemas:
    UnexpectedErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Internal server error.
    BadRequestResponse:
      type: object
      properties:
        message:
          type: string
    UnauthorizedResponse:
      type: object
      properties:
        message:
          type: string
      example:
        message: Invalid Authentication
    inline_response_404:
      properties:
        message:
          type: string
          example: Resource not found.
    inline_response_422:
      properties:
        message:
          type: string
    inline_response_500:
      properties:
        status:
          type: number
          example: 500
        message:
          type: string
          example: Internal Server Error
    urls_body:
      type: object
      properties:
        original_url:
          type: string
          example: http://some_random_url.com
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: apikey
      in: query
